#include"String.h"
using namespace std;
int main()
{
	cout << (3, 4, 5, 6);
	return 0;
	String st1{"abcdefghij"};
	String st2{ "def" };
	// st.setNumber(0);
	st1.resize(5);
	st1.display();
	//st.display();
	//cout << "Enter string:";
	//st.input();
	//st.trim();
	//st.reverse();
	//st.display();
	//cout << endl;
	//float n=st.convertToFloat();
	//cout << n;
	//cout<<endl<<st.size;
	//String subStr{"Muhammad Umer"};
	//st.display();
	//cout << endl;
	//String subStOld{ "a" };
	//String subStNew{(const char *)nullptr };
	//st.remove(0, 4);
	//cout<<st.convertToInteger();
	//st.display();
	//String resultSt = st.right(13);
	//resultSt.display();
	cout << "|||";
	//subStr.display();
	//cout << endl;
	//String resultingSt = st.concatenate(subStr);
	//resultingSt.display();
	/*st.display();
	cout << endl;
	subStr.display();
	cout << endl;
	resultingSt.display();
	*///cout << "|||";
	//st.display();
	//myMemCpy(&(st.data[0]),&(st.data[3]), 3);
	//st.display();
	//cout << "Enter string 2:";
	//subStr.input();
	//cout << st.compare(subStr) << endl;
	//cout << strcmp(st.data, subStr.data);
	//int cntOfBytes;
	//cout << "Enter count of bytes:";
	//cin >> cntOfBytes;
	//memcpy(st.data, subStr.data, cntOfBytes);
	//myMemCpy(st.data, subStr.data, cntOfBytes);
	//int index;
	//cout << "Enter index:";
	//cin >> index;
	//st.display();
	//cout << "|||";
	//st.trimRight();
	//st.insert(index , subStr);
	//int ind, cnt;
	//cout << "Enter index:";
	//cin >> ind;
	//cout << "enter count:";
	//cin >> cnt;
	//st.remove(ind, cnt);
	//st.display();
	//cout << "|||";
	//cout << endl;
	//subStr.display();
	//cout << "Enter substring:";
	//subStr.input();
	//cout << "Required index:" << st.find(subStr);
	//cout << "Size before trimRight():" << st.size;
	//cout << "\nLength before trimRight():" << st.getLength();
	//st.trimRight();
	//st.display();
	//cout << "\nSize after trimRight():" << st.size;
	//cout << "\nLength after trimRight():" << st.getLength();
	return 0;
};